# Generated by Django 3.2.5 on 2021-07-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_name', models.CharField(max_length=50)),
                ('serie_genre', models.CharField(max_length=50)),
                ('serie_rating', models.FloatField(max_length=5)),
                ('serie_info', models.TextField()),
                ('serie_note', models.TextField()),
            ],
        ),
    ]
