# Generated by Django 3.2.5 on 2021-07-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesreviews',
            name='serie_rating',
            field=models.IntegerField(max_length=5),
        ),
    ]
